wandb_version: 1

dense_layer_size:
  desc: null
  value: 128
dropout:
  desc: null
  value: 0.2
epochs:
  desc: null
  value: 10
first_layer_conv_height:
  desc: null
  value: 3
first_layer_conv_width:
  desc: null
  value: 3
first_layer_convs:
  desc: null
  value: 32
img_height:
  desc: null
  value: 28
img_width:
  desc: null
  value: 28
